CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    CREATE TABLE "DailyEntries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Date" date NOT NULL,
        "BrainDump" text,
        "Worries" text,
        "WorryTime" time without time zone,
        "Gratitude" text,
        CONSTRAINT "PK_DailyEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    CREATE TABLE "Goals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Type" text NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Goals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    CREATE TABLE "Priorities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Done" boolean NOT NULL,
        "DailyEntryId" integer NOT NULL,
        "Importance" integer NOT NULL,
        CONSTRAINT "PK_Priorities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Priorities_DailyEntries_DailyEntryId" FOREIGN KEY ("DailyEntryId") REFERENCES "DailyEntries" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    CREATE TABLE "Steps" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Text" text NOT NULL,
        "Done" boolean NOT NULL,
        "GoalId" integer NOT NULL,
        CONSTRAINT "PK_Steps" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Steps_Goals_GoalId" FOREIGN KEY ("GoalId") REFERENCES "Goals" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_DailyEntries_Date" ON "DailyEntries" ("Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    CREATE INDEX "IX_Priorities_DailyEntryId" ON "Priorities" ("DailyEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    CREATE INDEX "IX_Steps_GoalId" ON "Steps" ("GoalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111074837_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251111074837_InitialCreate', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122202702_AddRecurringPrioritiesWithCron') THEN
    ALTER TABLE "Priorities" ADD "RecurringPriorityId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122202702_AddRecurringPrioritiesWithCron') THEN
    CREATE TABLE "RecurringPriorities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "CronExpression" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "Importance" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RecurringPriorities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122202702_AddRecurringPrioritiesWithCron') THEN
    CREATE INDEX "IX_Priorities_RecurringPriorityId" ON "Priorities" ("RecurringPriorityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122202702_AddRecurringPrioritiesWithCron') THEN
    ALTER TABLE "Priorities" ADD CONSTRAINT "FK_Priorities_RecurringPriorities_RecurringPriorityId" FOREIGN KEY ("RecurringPriorityId") REFERENCES "RecurringPriorities" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251122202702_AddRecurringPrioritiesWithCron') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251122202702_AddRecurringPrioritiesWithCron', '9.0.10');
    END IF;
END $EF$;
COMMIT;

